export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUIRE_ROBOTS_PENDING = "REQUIRE_ROBOTS_PENDING";
export const REQUIRE_ROBOTS_SUCCESS = "REQUIRE_ROBOTS_SUCCESS";
export const REQUIRE_ROBOTS_FAILED = "REQUIRE_ROBOTS_FAILED";